# Generated by Django 6.0.3 on 2026-03-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='ower',
            new_name='owner',
        ),
    ]
