# Generated by Django 6.0.3 on 2026-03-26 11:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default=accounts.models.generate_verification_code, editable=False, max_length=6),
        ),
    ]
